app:
  openSkyUri: "https://USERNAME:PASSWORD@opensky-network.org/api/flights/arrival"
  airportCode: "LPPT"
  openSkyUri1: "https://USERNAME:PASSWORD@opensky-network.org/api/flights/departure"

spring:
  jpa:
    hibernate:
      ddl-auto: create #inicializa o schema da bd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:33060/ap_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://192.168.160.18:10001/ap_db?createDatabaseIfNotExist=true
    username: ap_user
    password: root
    initialization-mode: always